// Generated by opcodes.pl
	uint32_t vimm, vid, rs, cpr, wm, of, fsf, vfd, vft, vit, vcall, sa, bc, rt, vfs, vis, fs, fd, code, offset, fcr, base, ft, simm, branch, ftf, hint, zimm, rd, op;

	// Opcode tables:
	// Flags:
	//   D - has a delay slot
	//   L - likely delay slot behaviour
	//   E - ends control flow
	// MIPS opcodes
	// --- opcode --------------------------------|flag|--- disasm -----------------
	if ((opcode & 0xffffffff) == 0x00000000) { WRITE("\tnop\n"); return; }
	if ((opcode & 0xfc0007ff) == 0x00000020) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tadd %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x20000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\taddi %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x24000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\taddiu %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000021) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\taddu %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000024) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tand %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x30000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; zimm = (opcode >> 0) & 65535; WRITE("\tandi %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_zimm(zimm).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x10000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbeq %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x50000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbeql %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04010000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbgez %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04110000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbgezal %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04130000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbgezall %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04030000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbgezl %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x1c000000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbgtz %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x5c000000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbgtzl %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x18000000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tblez %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x58000000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tblezl %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04000000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbltz %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04100000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbltzal %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04120000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbltzall %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04020000) { rs = (opcode >> 21) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbltzl %s, %s\n", str_rs(rs).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x14000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbne %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x54000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbnel %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_branch(branch).c_str()); return; }
	if ((opcode & 0xfc00003f) == 0x0000000d) { code = (opcode >> 6) & 1048575; WRITE("\tbreak %s\n", str_code(code).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000002c) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tdadd %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x60000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\tdaddi %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x64000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\tdaddiu %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000002d) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tdaddu %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc00ffff) == 0x0000001a) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; WRITE("\tdiv %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc00ffff) == 0x0000001b) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; WRITE("\tdivu %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x00000038) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tdsll %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x0000003c) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tdsll32 %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000014) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tdsllv %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x0000003b) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tdsra %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x0000003f) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tdsra32 %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000017) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tdsrav %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x0000003a) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tdsrl %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x0000003e) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tdsrl32 %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000016) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tdsrlv %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000002e) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tdsub %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000002f) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tdsubu %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	// TODO: J/JAL
	if ((opcode & 0xfc1f07ff) == 0x00000009) { rs = (opcode >> 21) & 31; rd = (opcode >> 11) & 31; handle_D(); WRITE("\tjalr %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x00000008) { rs = (opcode >> 21) & 31; handle_D(); handle_E(); WRITE("\tjr %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x80000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlb %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x90000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlbu %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xdc000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tld %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x68000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tldl %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x6c000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tldr %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x84000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlh %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x94000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlhu %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xffe00000) == 0x3c000000) { rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\tlui %s, %s\n", str_rt(rt).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x8c000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlw %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x88000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlwl %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x98000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlwr %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x9c000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlwu %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x00000010) { rd = (opcode >> 11) & 31; WRITE("\tmfhi %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x00000012) { rd = (opcode >> 11) & 31; WRITE("\tmflo %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000000b) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmovn %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000000a) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmovz %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x00000011) { rs = (opcode >> 21) & 31; WRITE("\tmthi %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x00000013) { rs = (opcode >> 21) & 31; WRITE("\tmtlo %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000018) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmult %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000019) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmultu %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000027) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tnor %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000025) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tor %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x34000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\tor %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xcc000000) { base = (opcode >> 21) & 31; hint = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tpref %s, %s(%s)\n", str_hint(hint).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xa0000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tsb %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xfc000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tsd %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	// TODO: SDL/SDR
	if ((opcode & 0xfc000000) == 0xa4000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tsh %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x00000000) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tsll %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000004) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tsllv %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000002a) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tslt %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x28000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\tslti %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x2c000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; simm = (opcode >> 0) & 65535; WRITE("\tsltiu %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_simm(simm).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x0000002b) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tsltu %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x00000003) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tsra %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000007) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tsrav %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x00000002) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tsrl %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000006) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tsrlv %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000022) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tsub %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x00000023) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tsubu %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xac000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tsw %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	// TODO: SWL/SWR
	if ((opcode & 0xfffffc3f) == 0x0000000f) { WRITE("\tsync.l\n"); return; }
	if ((opcode & 0xfffffc3f) == 0x0000040f) { WRITE("\tsync.p\n"); return; }
	if ((opcode & 0xfc00003f) == 0x0000000c) { code = (opcode >> 6) & 1048575; WRITE("\tsyscall %s\n", str_code(code).c_str()); return; }
	// TODO: TEQ/TEQI/TGE/TGEI/TGEIU/TGEU/TLT/TLTI/TLTIU/TLTU/TNE/TNEI
	if ((opcode & 0xfc0007ff) == 0x00000026) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\txor %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x38000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; zimm = (opcode >> 0) & 65535; WRITE("\txor %s, %s, %s\n", str_rt(rt).c_str(), str_rs(rs).c_str(), str_zimm(zimm).c_str()); return; }
	// EE/MMI opcodes
	// --- opcode --------------------------------|flag|--- disasm -----------------
	if ((opcode & 0xfc00ffff) == 0x7000001a) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; WRITE("\tdiv1 %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc00ffff) == 0x7000001b) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; WRITE("\tdivu1 %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x78000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlq %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmadd %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000020) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmadd1 %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000001) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmaddu %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000021) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmaddu1 %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x70000010) { rd = (opcode >> 11) & 31; WRITE("\tmfhi1 %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x70000012) { rd = (opcode >> 11) & 31; WRITE("\tmflo1 %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x00000028) { rd = (opcode >> 11) & 31; WRITE("\tmfsa %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x70000011) { rs = (opcode >> 21) & 31; WRITE("\tmthi1 %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x70000013) { rs = (opcode >> 21) & 31; WRITE("\tmtlo1 %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x00000029) { rs = (opcode >> 21) & 31; WRITE("\tmtsa %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04180000) { rs = (opcode >> 21) & 31; zimm = (opcode >> 0) & 65535; WRITE("\tmtsab %s, %s\n", str_rs(rs).c_str(), str_zimm(zimm).c_str()); return; }
	if ((opcode & 0xfc1f0000) == 0x04190000) { rs = (opcode >> 21) & 31; zimm = (opcode >> 0) & 65535; WRITE("\tmtsah %s, %s\n", str_rs(rs).c_str(), str_zimm(zimm).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000018) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmult1 %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000019) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tmultu1 %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x70000168) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpabsh %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x70000068) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpabsw %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000208) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpaddb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000108) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpaddh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000608) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpaddsb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000508) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpaddsh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000408) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpaddsw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000628) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpaddub %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000528) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpadduh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000428) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpadduw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000008) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpaddw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000128) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpadsbh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000489) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpand %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700002a8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpceqb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700001a8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpceqh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700000a8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpceqw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000288) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpcgtb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000188) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpcgth %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000088) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpcgtw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x700006e9) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpcpyh %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000389) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpcpyld %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700003a9) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpcpyud %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc00ffff) == 0x70000749) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; WRITE("\tpdivbw %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc00ffff) == 0x70000369) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; WRITE("\tpdivuw %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc00ffff) == 0x70000349) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; WRITE("\tpdivw %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x700006a9) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpexch %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x700007a9) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpexcw %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x70000689) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpexeh %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x70000789) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpexew %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x70000788) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpext5 %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000688) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpextlb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000588) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpextlh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000488) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpextlw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700006a8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpextub %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700005a8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpextuh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700004a8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpextuw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000449) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tphmadh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000549) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tphmsbh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700002a9) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpinteh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000289) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpinth %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc1f07ff) == 0x70000004) { rs = (opcode >> 21) & 31; rd = (opcode >> 11) & 31; WRITE("\tplzcw %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000409) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmaddh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000029) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmadduw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000009) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmaddw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700001c8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmaxh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700000c8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmaxw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x70000209) { rd = (opcode >> 11) & 31; WRITE("\tpmfhi %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x700000f0) { rd = (opcode >> 11) & 31; WRITE("\tpmfhl.lh %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x70000030) { rd = (opcode >> 11) & 31; WRITE("\tpmfhl.lw %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x70000130) { rd = (opcode >> 11) & 31; WRITE("\tpmfhl.sh %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x700000b0) { rd = (opcode >> 11) & 31; WRITE("\tpmfhl.slw %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x70000070) { rd = (opcode >> 11) & 31; WRITE("\tpmfhl.uw %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x70000249) { rd = (opcode >> 11) & 31; WRITE("\tpmflo %s\n", str_rd(rd).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700001e8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpminh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700000e8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpminw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000509) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmsubh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000109) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmsubw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x70000229) { rs = (opcode >> 21) & 31; WRITE("\tpmthi %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x70000031) { rs = (opcode >> 21) & 31; WRITE("\tpmthl.lw %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc1fffff) == 0x70000269) { rs = (opcode >> 21) & 31; WRITE("\tpmtlo %s\n", str_rs(rs).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000709) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmulth %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000329) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmultuw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000309) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpmultw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700004e9) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpnor %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700004a9) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpor %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x700007c8) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tppac5 %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700006c8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tppacb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700005c8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tppach %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700004c8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tppacw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x700006c9) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tprevh %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x700007c9) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tprot3w %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x70000034) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tpsllh %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000089) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsllvw %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x7000003c) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tpsllw %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x70000037) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tpsrah %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700000e9) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsravw %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x7000003f) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tpsraw %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x70000036) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tpsrlh %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700000c9) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsrlvw %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_rs(rs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x7000003e) { rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; WRITE("\tpsrlw %s, %s, %s\n", str_rd(rd).c_str(), str_rt(rt).c_str(), str_sa(sa).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000248) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000148) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000648) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubsb %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000548) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubsh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000448) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubsw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000448) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubub %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000568) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubuh %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000468) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubuw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x70000048) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpsubw %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700004c9) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tpxor %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc0007ff) == 0x700006e8) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; WRITE("\tqfsrv %s, %s, %s\n", str_rd(rd).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x7c000000) { base = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tsq %s, %s(%s)\n", str_rt(rt).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	// COP0/MMU opcodes
	// --- opcode --------------------------------|flag|--- disasm -----------------
	if ((opcode & 0xffffffff) == 0x42000039) { WRITE("\tdi\n"); return; }
	if ((opcode & 0xffffffff) == 0x42000038) { WRITE("\tei\n"); return; }
	if ((opcode & 0xfc000000) == 0xbc000000) { base = (opcode >> 21) & 31; hint = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tcache %s, %s(%s)\n", str_hint(hint).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xffffffff) == 0x42000018) { WRITE("\teret\n"); return; }
	if ((opcode & 0xffe007ff) == 0x40000000) { rt = (opcode >> 16) & 31; cpr = (opcode >> 11) & 31; WRITE("\tmfc0 %s, %s\n", str_rt(rt).c_str(), str_cpr(cpr).c_str()); return; }
	if ((opcode & 0xffe0ffc1) == 0x4000c801) { rt = (opcode >> 16) & 31; cpr = (opcode >> 1) & 31; WRITE("\tmfpc %s, %s\n", str_rt(rt).c_str(), str_cpr(cpr).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x40800000) { rt = (opcode >> 16) & 31; cpr = (opcode >> 11) & 31; WRITE("\tmtc0 %s, %s\n", str_rt(rt).c_str(), str_cpr(cpr).c_str()); return; }
	if ((opcode & 0xffe0ffff) == 0x4080c004) { rt = (opcode >> 16) & 31; WRITE("\tmtdab %s\n", str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe0ffff) == 0x4080c005) { rt = (opcode >> 16) & 31; WRITE("\tmtdabm %s\n", str_rt(rt).c_str()); return; }
	if ((opcode & 0xffe0ffc1) == 0x4080c801) { rt = (opcode >> 16) & 31; cpr = (opcode >> 1) & 31; WRITE("\tmtpc %s, %s\n", str_rt(rt).c_str(), str_cpr(cpr).c_str()); return; }
	// TODO: the rest
	// COP1/FPU opcodes
	// --- opcode --------------------------------|flag|--- disasm -----------------
	if ((opcode & 0xffff003f) == 0x46000005) { fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tabs.s %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x46000000) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tadd.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x46000018) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tadda.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffff0000) == 0x45000000) { branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbc1f %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffff0000) == 0x45020000) { branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbc1fl %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffff0000) == 0x45010000) { branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbc1t %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffff0000) == 0x45030000) { branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbc1tl %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x46000032) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tc.eq.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x46000030) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tc.f.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x46000036) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tc.le.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x46000034) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tc.lt.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x44400000) { rt = (opcode >> 16) & 31; fcr = (opcode >> 11) & 31; WRITE("\tcfc1 %s, %s\n", str_rt(rt).c_str(), str_fcr(fcr).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x44c00000) { rt = (opcode >> 16) & 31; fcr = (opcode >> 11) & 31; WRITE("\tctc1 %s, %s\n", str_rt(rt).c_str(), str_fcr(fcr).c_str()); return; }
	if ((opcode & 0xffff003f) == 0x46800020) { fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tcvt.s.w %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str()); return; }
	if ((opcode & 0xffff003f) == 0x46000024) { fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tcvt.w.s %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x46000003) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tdiv.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xc4000000) { base = (opcode >> 21) & 31; ft = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlwc1 %s, %s(%s)\n", str_ft(ft).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4600001c) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tmadd.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x4600001e) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tmadda.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x46000028) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tmax.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x44000000) { rt = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tmfc1 %s, %s\n", str_rt(rt).c_str(), str_fs(fs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x46000029) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tmin.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffff003f) == 0x46000006) { fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tmov.s %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4600001d) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tmsub.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x4600001f) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tmsuba.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x44800000) { rt = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tmtc1 %s, %s\n", str_rt(rt).c_str(), str_fs(fs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x46000002) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tmul.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x4600001a) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tmula.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffff003f) == 0x46000007) { fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tneg.s %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x46000016) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\trsqrt.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe0f83f) == 0x46000004) { ft = (opcode >> 16) & 31; fd = (opcode >> 6) & 31; WRITE("\tsqrt.s %s, %s\n", str_fd(fd).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x46000001) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; fd = (opcode >> 6) & 31; WRITE("\tsub.s %s, %s, %s\n", str_fd(fd).c_str(), str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x46000019) { ft = (opcode >> 16) & 31; fs = (opcode >> 11) & 31; WRITE("\tsuba.s %s, %s\n", str_fs(fs).c_str(), str_ft(ft).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xe4000000) { base = (opcode >> 21) & 31; ft = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tswc1 %s, %s(%s)\n", str_ft(ft).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	// COP2/VU opcodes
	// --- opcode --------------------------------|flag|--- disasm --------------------
	if ((opcode & 0xffff0000) == 0x49000000) { branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbc2f %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffff0000) == 0x49020000) { branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbc2fl %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffff0000) == 0x49010000) { branch = (opcode >> 0) & 65535; handle_D(); WRITE("\tbc2t %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffff0000) == 0x49030000) { branch = (opcode >> 0) & 65535; handle_D(); handle_L(); WRITE("\tbc2tl %s\n", str_branch(branch).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48400000) { rt = (opcode >> 16) & 31; vid = (opcode >> 11) & 31; WRITE("\tcfc2 %s, %s\n", str_rt(rt).c_str(), str_vid(vid).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48400001) { rt = (opcode >> 16) & 31; vid = (opcode >> 11) & 31; WRITE("\tcfc2.i %s, %s\n", str_rt(rt).c_str(), str_vid(vid).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48c00000) { rt = (opcode >> 16) & 31; vid = (opcode >> 11) & 31; WRITE("\tctc2 %s, %s\n", str_rt(rt).c_str(), str_vid(vid).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48c00001) { rt = (opcode >> 16) & 31; vid = (opcode >> 11) & 31; WRITE("\tctc2.i %s, %s\n", str_rt(rt).c_str(), str_vid(vid).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xd8000000) { base = (opcode >> 21) & 31; vft = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tlqc2 %s, %s(%s)\n", str_vft(vft).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48200000) { rt = (opcode >> 16) & 31; vfd = (opcode >> 11) & 31; WRITE("\tqmfc2 %s, %s\n", str_rt(rt).c_str(), str_vfd(vfd).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48200001) { rt = (opcode >> 16) & 31; vfd = (opcode >> 11) & 31; WRITE("\tqmfc2.i %s, %s\n", str_rt(rt).c_str(), str_vfd(vfd).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48a00000) { rt = (opcode >> 16) & 31; vfd = (opcode >> 11) & 31; WRITE("\tqmtc2 %s, %s\n", str_rt(rt).c_str(), str_vfd(vfd).c_str()); return; }
	if ((opcode & 0xffe007ff) == 0x48a00001) { rt = (opcode >> 16) & 31; vfd = (opcode >> 11) & 31; WRITE("\tqmtc2.i %s, %s\n", str_rt(rt).c_str(), str_vfd(vfd).c_str()); return; }
	if ((opcode & 0xfc000000) == 0xf8000000) { base = (opcode >> 21) & 31; vft = (opcode >> 16) & 31; offset = (opcode >> 0) & 65535; WRITE("\tsqc2 %s, %s(%s)\n", str_vft(vft).c_str(), str_offset(offset).c_str(), str_base(base).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0001fd) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvabs.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003f) == 0x4a000028) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvadd.%s %s, %s, %s\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000022) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvaddi.%s %s, %s, I\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000020) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvaddq.%s %s, %s, Q\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003c) == 0x4a000000) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; bc = (opcode >> 0) & 3; WRITE("\tvadd%s.%s %s, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0002bc) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvadda.%s acc, %s, %s\n", str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00023e) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvaddai.%s acc, %s, I\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00023c) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvaddaq.%s acc, %s, Q\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007fc) == 0x4a00003c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; bc = (opcode >> 0) & 3; WRITE("\tvadda%s.%s acc, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4a000038) { vcall = (opcode >> 6) & 32767; WRITE("\tvcallms %s\n", str_vcall(vcall).c_str()); return; }
	if ((opcode & 0xffff07ff) == 0x4a000039) { vis = (opcode >> 11) & 31; WRITE("\tvcallmsr %s\n", str_vis(vis).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0001ff) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvclipw.xyz %s, %s\n", str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0003bc) { ftf = (opcode >> 23) & 3; fsf = (opcode >> 21) & 3; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvdiv Q, %s.%s, %s.%s\n", str_vfs(vfs).c_str(), str_fsf(fsf).c_str(), str_vft(vft).c_str(), str_ftf(ftf).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00017c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvftoi0.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00017d) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvftoi4.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00017e) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvftoi12.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00017f) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvftoi15.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4a000030) { vit = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; vid = (opcode >> 6) & 31; WRITE("\tviadd %s, %s, %s\n", str_vid(vid).c_str(), str_vis(vis).c_str(), str_vit(vit).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4a000032) { vit = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; vimm = (opcode >> 6) & 31; WRITE("\tviaddi %s, %s, %s\n", str_vit(vit).c_str(), str_vis(vis).c_str(), str_vimm(vimm).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4a000034) { vit = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; vid = (opcode >> 6) & 31; WRITE("\tviand %s, %s, %s\n", str_vid(vid).c_str(), str_vis(vis).c_str(), str_vit(vit).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0003fe) { wm = (opcode >> 21) & 15; vit = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; WRITE("\tvilwr.%s %s, (%s)\n", str_wm(wm).c_str(), str_vit(vit).c_str(), str_vis(vis).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4a000035) { vit = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; vid = (opcode >> 6) & 31; WRITE("\tvior %s, %s, %s\n", str_vid(vid).c_str(), str_vis(vis).c_str(), str_vit(vit).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4a000031) { vit = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; vid = (opcode >> 6) & 31; WRITE("\tvisub %s, %s, %s\n", str_vid(vid).c_str(), str_vis(vis).c_str(), str_vit(vit).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0003ff) { wm = (opcode >> 21) & 15; vit = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; WRITE("\tviswr.%s %s, (%s)\n", str_wm(wm).c_str(), str_vit(vit).c_str(), str_vis(vis).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00013c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvitof0.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00013d) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvitof4.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00013e) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvitof12.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00013f) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvitof15.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00037e) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; WRITE("\tvlqd.%s %s, (--%s)\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vis(vis).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00037c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; WRITE("\tvlqi.%s %s, (%s++)\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vis(vis).c_str()); return; }
	if ((opcode & 0xfe00003f) == 0x4a000029) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmadd.%s %s, %s, %s\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000023) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmaddi.%s %s, %s, I\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000021) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmaddq.%s %s, %s, Q\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003c) == 0x4a000008) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmadd%s.%s %s, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0002bd) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvmadda.%s acc, %s, %s\n", str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00023f) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvmaddai.%s acc, %s, I\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00023d) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvmaddaq.%s acc, %s, Q\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007fc) == 0x4a0000bc) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmadda%s.%s acc, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe00003f) == 0x4a00002b) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmax.%s %s, %s, %s\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a00001d) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmaxi.%s %s, %s, I\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003c) == 0x4a000010) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmax%s.%s %s, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0003fd) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vis = (opcode >> 11) & 31; WRITE("\tvmfir.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vis(vis).c_str()); return; }
	if ((opcode & 0xfe00003f) == 0x4a00002f) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmin.%s %s, %s, %s\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a00001f) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmini.%s %s, %s, I\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003c) == 0x4a000014) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmin%s.%s %s, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00033c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvmove.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00033d) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvmr32.%s %s, %s\n", str_wm(wm).c_str(), str_vft(vft).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003f) == 0x4a00002d) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmsub.%s %s, %s, %s\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000027) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmsubi.%s %s, %s, I\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000025) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmsubq.%s %s, %s, Q\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003c) == 0x4a00000c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmsub%s.%s %s, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0002fd) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvmsuba.%s acc, %s, %s\n", str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00027f) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvmsubai.%s acc, %s, I\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00027d) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvmsubaq.%s acc, %s, Q\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007fc) == 0x4a0000fc) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmsuba%s.%s acc, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xff8007ff) == 0x4a0003fc) { fsf = (opcode >> 21) & 3; vit = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvmtir %s, %s.%s\n", str_vit(vit).c_str(), str_vfs(vfs).c_str(), str_fsf(fsf).c_str()); return; }
	if ((opcode & 0xfe00003f) == 0x4a00002a) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmul.%s %s, %s, %s\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a00001e) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmuli.%s %s, %s, I\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a00001c) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvmulq.%s %s, %s, Q\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003c) == 0x4a000018) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmul%s.%s %s, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0002be) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvmula.%s acc, %s, %s\n", str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a0001fe) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvmulai.%s acc, %s, I\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a0001fc) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvmulaq.%s acc, %s, Q\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007fc) == 0x4a0001bc) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; bc = (opcode >> 0) & 3; WRITE("\tvmula%s.%s acc, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xffffffff) == 0x4a0002ff) { WRITE("\tvnop\n"); return; }
	if ((opcode & 0xffe007ff) == 0x4bc002fe) { vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvopmula.xyz acc, %s, %s\n", str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xffe0003f) == 0x4bc0002e) { vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvopmsub.xyz %s, %s, %s\n", str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe00ffff) == 0x4a00043d) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; WRITE("\tvrget.%s %s, R\n", str_wm(wm).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xff9f07ff) == 0x4a00043e) { fsf = (opcode >> 21) & 3; vfs = (opcode >> 11) & 31; WRITE("\tvrinit R, %s.%s\n", str_vfs(vfs).c_str(), str_fsf(fsf).c_str()); return; }
	if ((opcode & 0xfe00ffff) == 0x4a00043c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; WRITE("\tvrnext.%s %s, R\n", str_wm(wm).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0003be) { ftf = (opcode >> 23) & 3; fsf = (opcode >> 21) & 3; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvrsqrt Q, %s.%s, %s.%s\n", str_vfs(vfs).c_str(), str_fsf(fsf).c_str(), str_vft(vft).c_str(), str_ftf(ftf).c_str()); return; }
	if ((opcode & 0xff9f07ff) == 0x4a00043f) { fsf = (opcode >> 21) & 3; vfs = (opcode >> 11) & 31; WRITE("\tvrxor R, %s.%s\n", str_vfs(vfs).c_str(), str_fsf(fsf).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00037f) { wm = (opcode >> 21) & 15; vit = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvsqd.%s %s, (--%s)\n", str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vit(vit).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a00037d) { wm = (opcode >> 21) & 15; vit = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvsqi.%s %s, (%s++)\n", str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vit(vit).c_str()); return; }
	if ((opcode & 0xfe60ffff) == 0x4a0003bd) { ftf = (opcode >> 23) & 3; vft = (opcode >> 16) & 31; WRITE("\tvsqrt Q, %s.%s\n", str_vft(vft).c_str(), str_ftf(ftf).c_str()); return; }
	if ((opcode & 0xfe00003f) == 0x4a00002c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvsub.%s %s, %s, %s\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000026) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvsubi.%s %s, %s, I\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f003f) == 0x4a000024) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; WRITE("\tvsubq.%s %s, %s, Q\n", str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe00003c) == 0x4a000004) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; vfd = (opcode >> 6) & 31; bc = (opcode >> 0) & 3; WRITE("\tvsub%s.%s %s, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfd(vfd).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe0007ff) == 0x4a0002fc) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; WRITE("\tvsuba.%s acc, %s, %s\n", str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00027e) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvsubai.%s acc, %s, I\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe1f07ff) == 0x4a00027c) { wm = (opcode >> 21) & 15; vfs = (opcode >> 11) & 31; WRITE("\tvsubaq.%s acc, %s, Q\n", str_wm(wm).c_str(), str_vfs(vfs).c_str()); return; }
	if ((opcode & 0xfe0007fc) == 0x4a00007c) { wm = (opcode >> 21) & 15; vft = (opcode >> 16) & 31; vfs = (opcode >> 11) & 31; bc = (opcode >> 0) & 3; WRITE("\tvsuba%s.%s acc, %s, %s\n", str_bc(bc).c_str(), str_wm(wm).c_str(), str_vfs(vfs).c_str(), str_vft(vft).c_str()); return; }
	if ((opcode & 0xffffffff) == 0x4a0003bf) { WRITE("\tvwaitq\n"); return; }
	// Fallbacks
	// --- opcode --------------------------------|flag|--- disasm --------------------------------
	if ((opcode & 0xfc000000) == 0x00000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; of = (opcode >> 0) & 63; die("Unknown SPECIAL opcode %s, %s, %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_rd(rd).c_str(), str_sa(sa).c_str(), str_of(of).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x04000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; of = (opcode >> 0) & 63; die("Unknown REGIMM opcode %s, %s, %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_rd(rd).c_str(), str_sa(sa).c_str(), str_of(of).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x40000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; of = (opcode >> 0) & 63; die("Unknown COP0 opcode %s, %s, %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_rd(rd).c_str(), str_sa(sa).c_str(), str_of(of).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x44000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; of = (opcode >> 0) & 63; die("Unknown COP1 opcode %s, %s, %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_rd(rd).c_str(), str_sa(sa).c_str(), str_of(of).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x48000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; of = (opcode >> 0) & 63; die("Unknown COP2 opcode %s, %s, %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_rd(rd).c_str(), str_sa(sa).c_str(), str_of(of).c_str()); return; }
	if ((opcode & 0xfc000000) == 0x70000000) { rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; of = (opcode >> 0) & 63; die("Unknown MMI opcode %s, %s, %s, %s, %s\n", str_rs(rs).c_str(), str_rt(rt).c_str(), str_rd(rd).c_str(), str_sa(sa).c_str(), str_of(of).c_str()); return; }
	if ((opcode & 0x00000000) == 0x00000000) { op = (opcode >> 26) & 63; rs = (opcode >> 21) & 31; rt = (opcode >> 16) & 31; rd = (opcode >> 11) & 31; sa = (opcode >> 6) & 31; of = (opcode >> 0) & 63; die("Unknown MIPS opcode %s %s, %s, %s, %s, %s\n", str_op(op).c_str(), str_rs(rs).c_str(), str_rt(rt).c_str(), str_rd(rd).c_str(), str_sa(sa).c_str(), str_of(of).c_str()); return; }
	die("Missing decode handler for 0x%08x\n", opcode);
